/* eslint-disable */
// WARNING: Auto-generated by Amplify CLI. Run `amplify push` to regenerate.
const awsmobile = {
  aws_project_region: import.meta.env.VITE_AWS_REGION || 'us-east-1',
  aws_cognito_identity_pool_id:
    import.meta.env.VITE_COGNITO_IDENTITY_POOL_ID || '',
  aws_cognito_region: import.meta.env.VITE_COGNITO_REGION || 'us-east-1',
  aws_user_pools_id:
    import.meta.env.VITE_COGNITO_USER_POOL_ID || '',
  aws_user_pools_web_client_id:
    import.meta.env.VITE_COGNITO_WEB_CLIENT_ID || '',
  oauth: {
    domain: import.meta.env.VITE_COGNITO_DOMAIN || '',
    scope: [
      'phone',
      'email',
      'profile',
      'openid',
      'aws.cognito.signin.user.admin',
    ],
    redirectSignIn: import.meta.env.VITE_REDIRECT_SIGN_IN || 'http://localhost:5173/',
    redirectSignOut: import.meta.env.VITE_REDIRECT_SIGN_OUT || 'http://localhost:5173/',
    responseType: 'code',
  },
  aws_cognito_username_attributes: ['EMAIL'],
  aws_cognito_social_providers: ['GOOGLE'],
  aws_cognito_signup_attributes: ['EMAIL', 'NAME'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: [],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
}

export default awsmobile
